### ISSUE TITLE
Activation email flags spam systems

### ISSUE THREAD

**Issue by hlieberman** [PersonalGenomesOrg/open-humans#159]
Hello everyone!

It seems that the activation email is hitting the spam filters because of a misconfiguration in the rDNS on the mailserver.

outgoing.personalgenomes.org has a PTR record pointing to it, but there is no A record from outgoing.personalgenomes.org to 64.94.249.76.  This, in addition to the fact that activating accounts hits some of the anti-phishing flags, causes it to tip over the spam edge.  Adding an A record should solve that problem.

For reference, the spamassassin debug:
```
 pts rule name              description
---- ---------------------- --------------------------------------------------
 2.6 TVD_PH_SUBJ_ACCOUNTS_POST TVD_PH_SUBJ_ACCOUNTS_POST
 0.0 HTML_MESSAGE           BODY: HTML included in message
 1.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
 1.3 RDNS_NONE              Delivered to internal network by a host with no rDNS
 0.2 TO_NO_BRKTS_HTML_ONLY  To: misformatted and HTML only
 0.0 TO_NO_BRKTS_NORDNS     To: misformatted and no rDNS
```

The email headers:
```
Received: from outgoing.personalgenomes.org (unknown [64.94.249.76])
        by [snip] (Postfix) with ESMTPS id ECC5516A9B
	for [snip]; Wed, 25 Mar 2015 21:42:29 -0400 (EDT)
Date: Thu, 26 Mar 2015 01:42:28 +0000
From: PGP support <support@hu.pgp-hms.org>
To: [snip]
Message-ID: <5513640467653_1c6941e73ec39477@my-pgp-hms.shell.su92l.arvadosapi.com.mail>
Subject: Please activate your new account
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-detected-operating-system: by outgoing.pgp-hms.org: No matching host in p0f cache. That's all we know.
```

**Comment by beaugunderson** [comment]
I think this is one is a Tapestry-specific issue, but because I have access to the personalgenomes.org DNS I went ahead and added the A record. :)

**Comment by hlieberman** [comment]
Beat me to it, @beaugunderson.  I just got told that it was in the wrong place, but I didn't have time to move it before you fixed the problem!

**Comment by madprime** [comment]
I think PGP Harvard isn't supposed to be using a "personalgenomes.org" name anymore? Stuff was converted to "pgp-hms.org".  cc @cure

**Comment by cure** [comment]
This was caused by one remaining reference to outgoing.personalgenomes.org instead of outgoing.pgp-hms.org in the mailserver configuration on that machine. I fixed it. The A record for outgoing.pgp-hms.org existed already and is pointed at the correct IP.

@beaugunderson you can remove that outgoing.personalgenomes.org A record, it's no longer needed.

**Comment by beaugunderson** [comment]
@cure OK, it's been deleted now. :)
