### ISSUE TITLE
ensure that `next` parameter is carried forward when login form and signup form are reloaded

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#184]
@madprime got into a situation where she reloaded the login form after trying to get a password reset email and the `next` parameter was missing.

for example, a reload occurs if you don't click the "I accept the terms..." box.

**Comment by madprime** [comment]
This is still broken, at least on the login form. (I didn't test signup.)

To reproduce: Go to https://www.openhumans.org/account/login/?next=/welcome/ and try performing a failed log in.

**Comment by madprime** [comment]
This IS fixed. What's happening is that the "next" data is stored in a hidden form field, it's just no longer visible in the URL paramaters.
