### ISSUE TITLE
PGP Harvard detects connection broken on Open Humans end

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#195]
PGP Harvard should know when a connection was broken by the Open Humans member. Two ways....
  - Can detect if token is expired and cannot be refreshed. *But the current behavior needs to change* such that a refresh is automatically attempted, and if it fails, the user is assumed to have deauthorized the connection on OH’s end.
  - Or Open Humans could notify PGP Harvard site somehow (would need to build the ability to receive notification)

**Comment by beaugunderson** [comment]
Closing because we decided this is optional behavior on PGP's part and they now have the information needed to implement it.
