### ISSUE TITLE
GoViral: re-build registration form

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#206]
In https://www.goviralstudy.com/#sign-up the field ordering is messed up when the fields are collapsed to single column by Bootstrap (for xs and sm screen widths): 
* First name
* Password
* Last name
* Confirm password

Also,
* Email address
* Birthdate
* Confirm email address

Should use Bootstrap's "push" and "pull" to get correct order while having the same display on larger screen widths. http://getbootstrap.com/css/#grid-column-ordering

**Comment by beaugunderson** [comment]
Unfortunately not as easy as using push/pull since the fields are split up between columns that won't allow for easy re-ordering.

Shouldn't be too hard to re-build the form such that it makes sense in regular or collapsed form though, I'll add an estimate.
