### ISSUE TITLE
GoViral: simplelogin IDs for reports often do not match participants

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#211]
In the JSON dump of the Firebase data, many of the simplelogin IDs in 'reports' don't match the simplelogin IDs in 'participants'. (The former are the sickness reports associated with submitting samples, the latter contains participant information collected at signup.)

**Comment by beaugunderson** [comment]
- it looks like sometimes accounts could be created but the associated form data was not stored to Firebase
- I've deployed a version to production that displays an error in that case (but need to further diagnose why some form data is rejected)
- will update Rumi/Emily by EOD
- I think the current best plan is to extend the work for updating mailing addresses to allow updating all of the form data, and to send two versions of an email (one for people with form data already who might want to update their address, and an "action required" email for people with missing form data to fill it in)

**Comment by beaugunderson** [comment]
Rumi gave her OK to the above plan, I'll close this and update the issue for adding the mailing address.
