### ISSUE TITLE
PGP user flow update - bugs & redirect to Open Humans

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#225]
Per #224 we actually want all redirects going to Open Humans.

Currently testing in staging/dev servers, the origin parameter doesn't seem to be passed in the call the PGP site makes to Open Humans. Also there seems to be an error when the connection is revoked on Open Humans (rather than on PGP). 1st Q - is PGP dev running latest code here?

Regardless, an update to code at app/controllers/open_humans_controller.rb should occur so the user is always redirected to the Open Humans URL created by #224 (rather than only doing so based on origin).

**Comment by beaugunderson** [comment]
we need to know:

- what code is running on PGP staging?
- does origin parameter work?

**Comment by beaugunderson** [comment]
Ward wrote back and said that the Open Humans branch is now running on my-dev.pgp-hms.org.

**Comment by madprime** [comment]
Opened issues for:
- feature (change redirect behavior) https://dev.arvados.org/issues/7462
- bug (origin parameter seems to be dropped) https://dev.arvados.org/issues/7463

**Comment by madprime** [comment]
This is still open and should be done before we consider everything complete: https://dev.arvados.org/issues/7675

**Comment by beaugunderson** [comment]
Closing this as Open Humans shows on the [third-party activities page](https://my.pgp-hms.org/third_party/index) now.
