### ISSUE TITLE
What to do about existing connections from American Gut?

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#226]
We currently have barcodes, we will be getting survey_id. What should we do with the old barcode data?

Currently waiting on https://github.com/PersonalGenomesOrg/open-humans-data-processing/issues/15

**Comment by madprime** [comment]
Currently leaving old Barcode data, but it's no longer the "key data". Plan is to migrate this into the SurveyId model if/when we can. If we can't, should plan on killing the AG connection (i.e. revoke the tokens) for these old user connections.

**Comment by madprime** [comment]
#228 needs to be resolved before knowing what to do here.

**Comment by madprime** [comment]
Let's not worry about this until we confirm data import working for survey IDs - #258

**Comment by madprime** [comment]
A mapping of barcode to survey ID now exists here - we should use this to map existing data and trigger new data imports: https://github.com/PersonalGenomesOrg/open-humans-data-processing/blob/mb-update-amgut/data_retrieval/american-gut/barcodes_to_surveyids.json

**Comment by beaugunderson** [comment]
In our meeting this morning we decided to remove connections for anyone without Barcodes mapped to survey IDs, or no Barcodes at all.
