### ISSUE TITLE
Screenshots for updated AG process

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#232]
Series of screenshots for the following flows:

(1) User already has an Open Humans account, starts on Open Humans research data page, and seeks to connect American Gut.

(2) User is American Gut participant, starts on American Gut page, doesn't yet have an Open Humans account, and wants to connect their data to Open Humans.

**Comment by beaugunderson** [comment]
first set here: https://drive.google.com/drive/folders/0B4rjKh_X-C1sUW5OSHNnQ2FqSTA

(need to redo as this is a set that shows starting at American Gut but where the user already has an Open Humans profile)

**Comment by beaugunderson** [comment]
OK, both sets of screenshots are done and in separate folders now.
