### ISSUE TITLE
Send confirmation of connections

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#240]
When a connection is completed or removed for a study or activity, send user an email confirmation that the connection has been created or removed.

@madprime will provide a draft of the email text; @beaugunderson will implement it.

**Comment by beaugunderson** [comment]
Waiting on email draft from @madprime.

**Comment by madprime** [comment]
Draft for connection email: https://docs.google.com/document/d/1luC4hvuG-jJzkdAWktLu5vXQ6NGkdtTMv7KdT5DqQQQ/edit
