### ISSUE TITLE
Caching of members list page not working as well as it used to

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#253]
Currently getting application errors when loading the members list page.

**Comment by beaugunderson** [comment]
`EnrichedManager` needs `StudyGrant` added to the query, and needs to be tested to see what other queries it's making (if any).

**Comment by madprime** [comment]
Aside - adding to comments examples ("e.g. Keeping Pace as of Oct 2015") on line 117 and [line 127](https://github.com/PersonalGenomesOrg/open-humans/blob/7509e7b32e71ba109a4c8b6e9ac308cd2f1d3e24/open_humans/models.py#L127) would be helpful
