### ISSUE TITLE
Create more realistic test database for development

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#254]
Reflected in #253, we can sometimes see issues that only appear in production because our testing database is much smaller and/or lacks the "real world" situations encountered in production.

A solution to this could ideally be a de-identified version of production. But it's good enough to come up with a set of instructions for creating a fixture of the production db and using that to test (using data only people on our team can access).

**Comment by beaugunderson** [comment]
(we made some improvements here; if we want to make more we'll create a new issue that's more specific)
