### ISSUE TITLE
Think on & decide how DataFile model should work after redesign

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#266]
The principle: *the redesign should make it completely invisible to everyone but the admins that there’s anything other than a single file.*

"Maybe start with a document that literally lists every view, model, etc. that interacts datafile, comments on how update to this might look"

@beaugunderson will generate a list of how DataFile and its consumers will change (half day) and then @madprime and I will review it together.

**Comment by madprime** [comment]
Plan: meet after Tuesday Dec 1 stand-up to sketch this out.

**Comment by madprime** [comment]
Planned update outlined here: https://docs.google.com/document/d/1ji1desG5oLvrvXP3ePT4i6wv6ioGci4uV9ra75x-Jz8/edit
