### ISSUE TITLE
make subtype a CharField in BaseDataFile

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#270]
Currently `subtype` is [defined as None in BaseDataFile](https://github.com/PersonalGenomesOrg/open-humans/blob/311bad53cf6aec8be91abf0dcd4502c7d943b7a9/data_import/models.py#L229).

Child models define `subtype` as CharFields with defaults:
 - [in american_gut](https://github.com/PersonalGenomesOrg/open-humans/blob/311bad53cf6aec8be91abf0dcd4502c7d943b7a9/studies/american_gut/models.py#L74)
 - [in go_viral](https://github.com/PersonalGenomesOrg/open-humans/blob/311bad53cf6aec8be91abf0dcd4502c7d943b7a9/studies/go_viral/models.py#L76)

... or without default:
 - [in pgp](https://github.com/PersonalGenomesOrg/open-humans/blob/311bad53cf6aec8be91abf0dcd4502c7d943b7a9/studies/pgp/models.py#L81)

... or, unfortunately, not at all:
 - [in runkeeper](https://github.com/PersonalGenomesOrg/open-humans/blob/311bad53cf6aec8be91abf0dcd4502c7d943b7a9/activities/runkeeper/models.py#L53)

The last results in no subtype storage for RunKeeper data. When [this line attempts to set it](https://github.com/PersonalGenomesOrg/open-humans/blob/691f38e9cb990d3819abc116e2286d76916acb0f/data_import/views.py#L94), I believe it's actually setting an object attribute (which is lost).

I think the default for BaseDataFile should be as defined by `studies.pgp.models`.

**Comment by beaugunderson** [comment]
question: can we move the subtype field to `BaseDataFile` and retain defaults if we make a `get_default` method and let the subclassing models override it?
