### ISSUE TITLE
Integration: Wildlife of Our Homes

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#31]

**Comment by madprime** [comment]
Currently stalled on finding a public repository for some or all of the data.

A serious complication in releasing the data was the need for access to control samples (blanks) that were run alongside actual samples. The data from these samples indicates contaminating DNA sequences that should be subtracted from real samples. So, for a participant to share a sample, it's meaningless if there isn't theoretically access to the relevant blank.

The blanks could be publicly available somewhere -- in fact, all samples could be, in a de-identified manner. But the informatics team members reported there was no repository they could use. I suggested FigShare and, although this data is large compared to private FigShare data size limits, theoretically there is no limit to public data. As of today, haven't heard back regarding the status here.
