### ISSUE TITLE
Look at connect/connection language; investigate how hard it would be to only refer to data_import connections

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#318]
For example, the StudyGrant flow currently refers to "connecting" and "connections" but really it's just authorizing grants; better to use that terminology because it's more specific and doesn't have crossover with `data_import`.

There's also confusion around the term "deeply integrated studies".

**Comment by madprime** [comment]
Maybe try to clarify "data import" vs "grant" whenever possible.
