### ISSUE TITLE
Failed 23andMe processing

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#371]
Reported by a user in Desk ticket 235.

**Comment by madprime** [comment]
User's data was a Zip archive. Data processing asserts that Zip archives must contain one and only one file (to be unambiguous), and this archive violated the assertion. This occurred because it was (presumably) constructed on OSX and contained the __MACOSX directory. To avoid this issue, we should ignore this directory (if it exists) when counting and processing a Zip archive.

**Comment by madprime** [comment]
Fixed by https://github.com/PersonalGenomesOrg/open-humans-data-processing/commit/ee32f78e5668f1776e6687ec5f2e0494a1efe8a5

**Comment by beaugunderson** [comment]
@madprime I wonder if it's worth keeping a list of 'extraneous' files, like `.DS_Store` that could end up in a zip file?

**Comment by madprime** [comment]
@beaugunderson Oh, is that another one? I should get a reference list of hidden cruft directories and files OSX automatically adds that's invisible to OSX users. :(
