### ISSUE TITLE
Add Illumina UYG data processing

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#456]
We should sort the genome data. I've seen genomes with chrM or chr13 first. I want Open Humans to produce VCF data that's always: chr1 … chr9, chr10… chr19, chrX, chrY, chrM.

I think a sort was created for AncestryDNA, maybe can be used here.

Also, file validation: #443

**Comment by beaugunderson** [comment]
For a first past we'll add a check for the right name and size.

**Comment by beaugunderson** [comment]
This is in processing now on staging; I'll test it on the staging site.

**Comment by beaugunderson** [comment]
Noting that Illumina should remain `in_development` until the strict positive validation is done.

**Comment by madprime** [comment]
Obsolete as of the addition of the Genome/exome data sharing app.
