### ISSUE TITLE
Add uBiome data processing

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#460]
- [x] Check ~~file size and~~ file names.
- [ ] Check the JSON copy/paste is valid. Put it into a file.
- [ ] Check that the uploaded FASTQ looks like a FASTQ file. We'll want to share a copy of this file. Most secure method is to create copy via positive filter where each header and data line must match what we expect to see.

**Comment by beaugunderson** [comment]
We added sending data to data processing via POST to Open Humans to support sending the taxonomy data to uBiome (OH previously sent the data via querystring which errored out). The uBiome module currently checks that all files in the zip file end in `.fastq.gz` which we've decided is good enough (no need for a file size check).

The remaining piece is that the uBiome module needs to store the taxonomy data sent from Open Humans.
