### ISSUE TITLE
"next" isn't retained when login form fails

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#469]
If the user enters an incorrect username/password on the login page `/account/login/` the "next" parameter isn't retained.

**Comment by beaugunderson** [comment]
I can't reproduce this... Note that this issue came up before; it's normal for the `next` parameter to be removed the query parameter after the failed login attempt because it has moved to a hidden form input at that point:

![screenshot](https://i.imgur.com/m1H1iUH.png)

**Comment by madprime** [comment]
I forgot. Whoops.
