### ISSUE TITLE
Old 16 digit project member ID triggers error

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#478]
The Message Project Members feature isn't working for a pre-existing direct sharing project that has a 16 digit ID.

**Comment by beaugunderson** [comment]
@madprime fixed in dfc51a65f80ec2964d2e1ddb25515e7da8a27c88; OK to deploy to production? (this would mean mPower would get deployed as well, or I can cherry pick just this fix...)

**Comment by madprime** [comment]
Yeah... I'd like to see this deployed this morning, but can you give mPower a run-through on staging? Pretend to be a naive user, follow the data retrieval and upload instructions. Afterwards, double-check that the file shows up in the database post-upload.

(Deploying mPower helps with communications, we want to let GET Labs attendees know they should hook up sources/studies to show up on their badges.)

**Comment by beaugunderson** [comment]
Updated the mPower docs and fixed a small bug :)
