### ISSUE TITLE
bulk_tasks command not working for social auth apps

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#489]
e.g. https://app.getsentry.com/openhumansorg/oh-production/issues/126745540/

This error arose when trying to use the 'bulk_tasks' management command for the 'moves' app.

**Comment by beaugunderson** [comment]
I see the issue here--when we made the `UserData` class for `UserSocialAuth` activities a non-model we broke  `bulk_tasks` for those activities. Simple fix, I think. :)

**Comment by madprime** [comment]
I thought runkeeper worked for me -- which left me confused -- maybe I'm misremembering.
