### ISSUE TITLE
Only return the most recent data set in Public Data API

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#491]
When I do this, I see all the files from data import tasks, not the most recent set:

https://www.openhumans.org/api/public-data/?source=pgp&member=mpball

**Comment by madprime** [comment]
I believe this line of the optimization in February has a typo bug. The `user_task` should be updated to have `is_latest=False`. Not the `task` – which refers to the latest task, which we actually want to retain as the only `is_latest=True`.

https://github.com/PersonalGenomesOrg/open-humans/blame/master/data_import/views.py#L65

**Comment by beaugunderson** [comment]
:+1: on the analysis and the proposed fix :)

**Comment by madprime** [comment]
Fixed by 3e0eac1

**Comment by madprime** [comment]
Fixed by 3e0eac1
