### ISSUE TITLE
Implement OAuth2 expiration/refresh flow for project master access tokens 

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#496]
Our short term plan involves adding a refresh button so that project leaders can invalidate their old master access token and get a new master access token at any time through the Open Humans website.

Our long term plan is to implement the OAuth2 expiration/refresh flow for these tokens so that automatic expiration is enforced and project leaders can get a new token via the refresh process.

**Comment by madprime** [comment]
Closing in favor of #495 – and we want it to be permanent (don't enable automation via refresh)
