### ISSUE TITLE
Can't enter an app-launching URI for a Redirect URL

### ISSUE THREAD

**Issue by blackbear** [PersonalGenomesOrg/open-humans#502]
If you want to create an OAUTH2 project that uses an iOS app launch URL as the redirect URL, you can't, because the web page won't accept it as a valid URL:

![screen shot 2016-06-01 at 2 01 09 pm](https://cloud.githubusercontent.com/assets/109585/15720205/59a1fbb6-2801-11e6-8df4-d2bb44b3dd66.png)

**Comment by beaugunderson** [comment]
Narrowed this down to a Parsley/browser issue; we use a `URLField` in the model which translates to an `input` with `type="url"` when the form is rendered. For some reason Parsley and Chrome expect that a valid URL will always begin with `http://` or `https://`, so we need to override `type="url"` and specify our own regex (or be OK with no validation).
