### ISSUE TITLE
Investigate how to handle OAuth2 tokens for phone apps

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#524]
We need to figure out how to support phone apps using the implicit grant flow for OAuth2 without inconveniencing users by making them re-authorize more often than needed.

We should see what other apps are doing in this regard.

We'll need to do this before making James' HealthKit importer live.

**Comment by madprime** [comment]
Based on the research, we've found there is no ideal solution. There are a variety of practices out there struggling to balance OAuth2 security, enabling mobile apps, and user experience.

After considering these, we think it's best to go ahead with enabling `authorization_code` grant flow for mobile apps.

The main reason for this is usability. Re-authorization by the user is not repeatedly required to keep the app authorized in an ongoing manner. (An implicit grant flow would have this issue.) The potential downside occurs if a phone is compromised – in this scenario, an attacker could access the same API features (for this particular user) that the app has authorization for. We think this is a remote scenario.

To compare to another entity handling similar data: 23andMe offers data access via API. Their API only offers an `authorization_code` grant type, and allows non-http URLs for mobile app callbacks.

An authorization_code flow for mobile apps would match their own practices. In fact, we believe we would be more secure than their own API configuration, as we redirect HTTP to HTTPS within Open Humans and disallow any HTTP (unencrypted) callback URLs. This protects our tokens from being leaked through unencrypted traffic.
