### ISSUE TITLE
Better warning on MASTER_ACCESS_TOKEN

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#530]
Maybe a bold warning right next to it in the project information page like...

**Do NOT share this token publicly. Do NOT share it in unencrypted email. Do NOT put it in a git repository. Store it as securely as possible!**

**Comment by madprime** [comment]
**Do NOT store this token unless you can do it securely. Do NOT share it in unencrypted email. Do NOT put it in a git repository.**

Add above text immediately below where the token is displayed. Add a button to click to say "reveal token". Reveal the token after clicking the button.

**Comment by beaugunderson** [comment]
For the 'reveal' button I'd use something like this:

http://getbootstrap.com/components/#input-groups-buttons

**Comment by madprime** [comment]
Closing in favor of #495
