### ISSUE TITLE
Change post auth URL template to use PROJECT_MEMBER_ID

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#536]
Instead of OH_PROJECT_MEMBER_ID. This makes it consistent with the messaging template.

Once changed, check the post authorization URLs for existing projects on the site and fix if needed.

**Comment by beaugunderson** [comment]
Just updated the 6 projects using OH_PROJECT_MEMBER_ID to PROJECT_MEMBER_ID.
