### ISSUE TITLE
Keeping Pace shows 0 connections on the Homepage. 

### ISSUE THREAD

**Issue by hopekroog** [PersonalGenomesOrg/open-humans#540]
Should be ~74

**Comment by madprime** [comment]
It looks like this was broken by the changes made to direct project "labels" in 058ea7ec

The label was updated in the badge data here: https://github.com/PersonalGenomesOrg/open-humans/commit/058ea7ec47dbfe7bafb520217014356c4eb30e7d#diff-5ce9a44ecdca10677dba0a3b823e5526L176

But the counts algorithm here wasn't similarly updated: https://github.com/PersonalGenomesOrg/open-humans/blob/058ea7ec47dbfe7bafb520217014356c4eb30e7d/common/activities.py#L127
