### ISSUE TITLE
App-based data sources to "projects" infrastructure w/"InternalProject"

### ISSUE THREAD

**Issue by beaugunderson** [PersonalGenomesOrg/open-humans#549]
Enables us to represent all integrations as "projects".

This means data-processing could also change to use the projects API for data file upload/management.

**Comment by madprime** [comment]
Instead of creating "InternalProject" model, we're working on the API portions specifically: creating endpoints to query current files and receive files, the same way projects interact. This involves tearing out the current task-based file management.
