### ISSUE TITLE
Make "activity-direct-sharingXX" More descriptive

### ISSUE THREAD

**Issue by BenjaminHCCarr** [PersonalGenomesOrg/open-humans#568]
The current links aren't always, many are numeric activity-direct-sharingXX links are, their isn't a standard uniform format:

activity-direct-sharing2 is for Circles

activity-pgp is for Personal Genome Project

This may be related to: #483

**Comment by beaugunderson** [comment]
the `direct-sharing` links are for research projects created by third parties; we chose to use numeric IDs there because it's possible for the title of a project to change (which makes generating a URL slug from the title problematic)

**Comment by BenjaminHCCarr** [comment]
ah okay, that makes much more sense, also eases sanitizing the input and making sure it's G rated without input, though I am sure they all get reviewed anyway.
