### ISSUE TITLE
Restore "sort by badge count" to members list

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#853]
The update for badges (#846) seems to have introduced an inefficiency that's causing all member list pages to time out. This may be causing site-wide timeouts as servers get clogged on these requests.

1. Remove URL path for the list for now (it won't work anyway)
2. Fix the code so this works

**Comment by jhdulaney** [comment]
Noting that the reason for this is that we are sorting the members list within Python, which causes the queryset to resolve.  The true solution will require doing the sort within the database.  This should be possible by annotating each member with a badge count that can be done entirely within the queryset.
